default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  username: postgres
  password: password
  database: mayomayo_step_development

test:
  <<: *default
  host: db
  username: postgres
  password: password
  database: mayomayo_step_test

production:
  url: <%= ENV["DATABASE_URL"] %>
